[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[profile.remappings] 
 "@openzeppelin/" = "../lib/openzeppelin-contracts/"
  "@ethsign/" = "../lib/sign-protocol-evm/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
